### ISSUE TITLE
Quantum force

### ISSUE THREAD

**Issue by annasro** [kmaasrud/vmc#22]
For  importance sampling

**Comment by amundmr** [comment]
Harru titta i appendix? Der tror i at i finn QF for importance, litt usikker faktisk

**Comment by annasro** [comment]
> Harru titta i appendix? Der tror i at i finn QF for importance, litt usikker faktisk

Nei, det brude jeg har gjort! La det bare inn her s.a. vi ikke glemmer det i rapporten (tenkte det hadde passet i teorien)

**Comment by kmaasrud** [comment]
Vi kan referere til teori om importance sampling i prosjekt 1? Og så ha utledningen som @amundmr har mekka i appendiks! Er vel unødvendig å skrive på nytt, tror vi fikk refs for det i compphys 1...

**Comment by annasro** [comment]
> Vi kan referere til teori om importance sampling i prosjekt 1? Og så ha utledningen som @amundmr har mekka i appendiks! Er vel unødvendig å skrive på nytt, tror vi fikk refs for det i compphys 1...

Kan hende det er greit å bare ha selve utrykket i teorien? Det er der nå, men bare å ta bort hvis dere mener det er bedre uten
